<?php

return [
    'table_name' => 'jobs',

    'drop_scheme' => "SET FOREIGN_KEY_CHECKS = 0; DROP TABLE IF EXISTS `jobs`; SET FOREIGN_KEY_CHECKS = 1",

    'scheme' => "CREATE TABLE IF NOT EXISTS `jobs` (
        `id` int(11) NOT NULL AUTO_INCREMENT,
        `user_id` int NOT NULL,
        `start_year` year NOT NULL,
        `end_year` year DEFAULT NULL,
        `job` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
        `company` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
        `info` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
        `created` timestamp NOT NULL,
        `updated` timestamp DEFAULT CURRENT_TIMESTAMP,
        `deleted` timestamp DEFAULT NULL,
        `created_by` int(11) NOT NULL,
        `updated_by` int(11),
        `deleted_by` int(11),
        PRIMARY KEY (`id`)
      ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;",

    'relations' => [
        'ALTER TABLE `jobs` ADD FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;',
        'ALTER TABLE `jobs` ADD FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;',
        'ALTER TABLE `jobs` ADD FOREIGN KEY (`updated_by`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;',
        'ALTER TABLE `jobs` ADD FOREIGN KEY (`deleted_by`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;',
    ],

    'seeder' => [
        'type' => 'array',
        'data' => array([
            'user_id'       => 1,
            'start_year'    => 2001,
            'end_year'      => 2015,
            'job'           => 'Barman',
            'company'       => 'Pier',
            'info'          => 'op Terschelling',          
            'created'       => date('Y-m-d H:i:s'),
            'created_by'    => 1,
        ],
        [
            'user_id'       => 1,
            'start_year'    => 2016,
            'end_year'      => 2019,
            'job'           => 'Chef bier',
            'company'       => 'de Walvis',
            'info'          => 'in West-Terschelling',          
            'created'       => date('Y-m-d H:i:s'),
            'created_by'    => 1,
        ],
        [
            'user_id'       => 1,
            'start_year'    => 2020,
            'job'           => 'Mentor',
            'company'       => 'CodeGorilla',
            'info'          => 'in Groningen',          
            'created'       => date('Y-m-d H:i:s'),
            'created_by'    => 1,
        ],
        [
            'user_id'       => 2,
            'start_year'    => 2007,
            'end_year'      => 2012,
            'job'           => 'Orderpicker',
            'company'       => 'Noordhoff Uitgevers',
            'info'          => 'in het distributiecentrum in Groningen',          
            'created'       => date('Y-m-d H:i:s'),
            'created_by'    => 2,
        ],
        [
            'user_id'       => 2,
            'start_year'    => 2016,
            'end_year'      => 2019,
            'job'           => 'Orderpicker',
            'company'       => 'Muelink en Grol',
            'info'          => 'in Groningen',          
            'created'       => date('Y-m-d H:i:s'),
            'created_by'    => 2,
        ],
        [
            'user_id'       => 2,
            'start_year'    => 2010,
            'end_year'      => 2010,
            'job'           => 'Postbezorger',
            'company'       => 'TPG post',
            'info'          => 'in Buitenpost',          
            'created'       => date('Y-m-d H:i:s'),
            'created_by'    => 2,
        ],
        [
            'user_id'       => 3,
            'start_year'    => 1990,
            'end_year'      => 2000,
            'job'           => 'Olifantenbewaker',
            'company'       => 'Artis',
            'info'          => 'Amsterdam',          
            'created'       => date('Y-m-d H:i:s'),
            'created_by'    => 3,
        ],
        [
            'user_id'       => 3,
            'start_year'    => 2000,
            'end_year'      => 2010,
            'job'           => 'Olifantenmelker',
            'company'       => 'Diergaarde Blijdorp',
            'info'          => 'in Rotterdam',          
            'created'       => date('Y-m-d H:i:s'),
            'created_by'    => 3,
        ],
        [
            'user_id'       => 3,
            'start_year'    => 2010,
            'end_year'      => 2020,
            'job'           => 'Beveiliger',
            'company'       => 'PinkPop',
            'info'          => 'in Landgraaf',          
            'created'       => date('Y-m-d H:i:s'),
            'created_by'    => 3,
        ])
    ],
];