<?php

return [
    'table_name' => 'volunteer_jobs',

    'drop_scheme' => "SET FOREIGN_KEY_CHECKS = 0; DROP TABLE IF EXISTS `volunteer_jobs`; SET FOREIGN_KEY_CHECKS = 1",

    'scheme' => "CREATE TABLE IF NOT EXISTS `volunteer_jobs` (
        `id` int(11) NOT NULL AUTO_INCREMENT,
        `user_id` int NOT NULL,
        `start_year` year NOT NULL,
        `end_year` year DEFAULT NULL,
        `job` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
        `organization` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
        `info` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
        `created` timestamp NOT NULL,
        `updated` timestamp DEFAULT CURRENT_TIMESTAMP,
        `deleted` timestamp DEFAULT NULL,
        `created_by` int(11) NOT NULL,
        `updated_by` int(11),
        `deleted_by` int(11),
        PRIMARY KEY (`id`)
      ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;",

    'relations' => [
        'ALTER TABLE `volunteer_jobs` ADD FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;',
        'ALTER TABLE `volunteer_jobs` ADD FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;',
        'ALTER TABLE `volunteer_jobs` ADD FOREIGN KEY (`updated_by`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;',
        'ALTER TABLE `volunteer_jobs` ADD FOREIGN KEY (`deleted_by`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;',
    ],

    'seeder' => [
        'type' => 'array',
        'data' => array([
            'user_id'       => 1,
            'start_year'    => 2002,
            'end_year'      => 2012,
            'job'           => 'Schoonmaakhulp',
            'organization'  => 'de Poetsers',
            'info'          => 'in Leeuwarden',          
            'created'       => date('Y-m-d H:i:s'),
            'created_by'    => 1,
        ],
        [
            'user_id'       => 1,
            'start_year'    => 2016,
            'job'           => 'Rondleidingen geven',
            'organization'  => 'Noordelijk scheepvaartmuseum',
            'info'          => 'in Groningen',          
            'created'       => date('Y-m-d H:i:s'),
            'created_by'    => 1,
        ],
        [
            'user_id'       => 2,
            'start_year'    => 2005,
            'end_year'      => 2020,
            'job'           => 'lid JeugdBegeleidingsGroep',
            'organization'  => 'kv Flamingos',
            'info'          => 'in Buitenpost',          
            'created'       => date('Y-m-d H:i:s'),
            'created_by'    => 2,
        ],
        [
            'user_id'       => 2,
            'start_year'    => 2004,
            'end_year'      => 2019,
            'job'           => 'trainer/coach',
            'organization'  => 'kv Flamingos',
            'info'          => 'in Buitenpost',          
            'created'       => date('Y-m-d H:i:s'),
            'created_by'    => 2,
        ],
        [
            'user_id'       => 2,
            'start_year'    => 2006,
            'end_year'      => 2010,
            'job'           => 'Barmedewerker',
            'organization'  => 'kv Flamingos',
            'info'          => 'op de vrijdagavonden',          
            'created'       => date('Y-m-d H:i:s'),
            'created_by'    => 2,
        ],
        [
            'user_id'       => 2,
            'start_year'    => 2021,
            'job'           => 'Penningmeester',
            'organization'  => 'de Clubbinders',
            'info'          => 'supportersvereniging van kv Flamingos in Buitenpost',          
            'created'       => date('Y-m-d H:i:s'),
            'created_by'    => 2,
        ],
        [
            'user_id'       => 3,
            'start_year'    => 1990,
            'end_year'      => 2000,
            'job'           => 'voorleeshulp',
            'organization'  => 'bibliotheek',
            'info'          => 'in Zuidhorn',          
            'created'       => date('Y-m-d H:i:s'),
            'created_by'    => 3,
        ],
        [
            'user_id'       => 3,
            'start_year'    => 2000,
            'end_year'      => 2010,
            'job'           => 'penningmeester',
            'organization'  => 'Greenpeace',
            'info'          => 'afdeling Assen',          
            'created'       => date('Y-m-d H:i:s'),
            'created_by'    => 3,
        ],
        [
            'user_id'       => 3,
            'start_year'    => 2010,
            'end_year'      => 2020,
            'job'           => 'voorzitter',
            'organization'  => 'FC Groningen',
            'info'          => 'in Zwolle',          
            'created'       => date('Y-m-d H:i:s'),
            'created_by'    => 3,
        ])
    ],
];